# Generated by Django 4.2.7 on 2023-12-10 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dicom_web", "0002_remove_dicomwebsettings_slot_begin_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dicomwebsettings",
            options={
                "permissions": [
                    ("can_query", "Can query"),
                    ("can_retrieve", "Can retrieve"),
                    ("can_store", "Can store"),
                ],
                "verbose_name_plural": "Dicom Web settings",
            },
        ),
    ]
