from .base import *  # pylint: disable=wildcard-import,unused-wildcard-import
from .base import env

# Production settings, see
# https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

DEBUG = False

SECRET_KEY = env("DJANGO_SECRET_KEY")

ALLOWED_HOSTS = env.list("DJANGO_ALLOWED_HOSTS")

# TODO provide SMTP details, see https://docs.djangoproject.com/en/dev/topics/email/
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# For SSL encryption (generated by "generate_cert" management command)
CERT_PEM_FILE = "/var/www/adit/ssl/cert.pem"
KEY_PEM_FILE = "/var/www/adit/ssl/key.pem"
