# Generated by Django 3.1.3 on 2021-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210128_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='coresettings',
            name='announcement',
            field=models.TextField(blank=True),
        ),
    ]
