# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0007_dicom_node_institute_access"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueuedTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("priority", models.PositiveIntegerField()),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["eta", "priority", "created"], name="eta_priority_created_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="queuedtask",
            constraint=models.UniqueConstraint(
                fields=("content_type", "object_id"), name="unique_queued_task_per_dicom_task"
            ),
        ),
    ]
