# Generated by Django 4.2.7 on 2023-11-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_queuedtask_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="queuedtask",
            name="eta_priority_created_idx",
        ),
        migrations.AddField(
            model_name="queuedtask",
            name="locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="queuedtask",
            index=models.Index(
                fields=["locked", "eta", "priority", "created"], name="fetch_next_task_idx"
            ),
        ),
    ]
