# Generated by Django 4.2.11 on 2024-03-26 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_queuedtask_kill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoreSettings',
        ),
    ]
