# Generated by Django 5.0.6 on 2024-07-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_delete_coresettings"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QueuedTask",
        ),
    ]
