# Generated by Django 4.2.3 on 2023-07-23 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0006_rename_expiry_time_token_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="last_used",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
