# Generated by Django 4.2.3 on 2023-07-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0007_alter_token_last_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="token_hashed",
            field=models.TextField(max_length=128, unique=True),
        ),
    ]
