# Generated by Django 3.1.1 on 2020-09-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomserver',
            name='patient_root_query_model_find',
        ),
        migrations.RemoveField(
            model_name='dicomserver',
            name='patient_root_query_model_get',
        ),
        migrations.RemoveField(
            model_name='dicomserver',
            name='patient_root_query_model_move',
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='patient_root_find_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='patient_root_get_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='patient_root_move_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='study_root_find_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='study_root_get_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='study_root_move_support',
            field=models.BooleanField(default=True),
        ),
    ]
