# Generated by Django 3.0.7 on 2020-08-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='archive_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='trial_protocol_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='trial_protocol_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
