# Generated by Django 3.0.7 on 2020-08-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200825_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertask',
            name='log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='status',
            field=models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('IP', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='UV', max_length=2),
        ),
        migrations.AlterField(
            model_name='transfertask',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CA', 'Canceled'), ('SU', 'Success'), ('FA', 'Failure')], default='PE', max_length=2),
        ),
    ]
