# Generated by Django 3.1.2 on 2020-10-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201023_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomnode',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='transfertask',
            options={'ordering': ('id',)},
        ),
    ]
