# Generated by Django 3.1.2 on 2020-10-04 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200924_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='job_type',
            field=models.CharField(choices=[('ST', 'Selective Transfer'), ('BT', 'Batch Transfer'), ('CT', 'Continuous Transfer')], max_length=2),
        ),
    ]
