# Generated by Django 3.1.2 on 2020-10-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201023_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomfolder',
            name='quota',
            field=models.PositiveIntegerField(blank=True, help_text='The disk quota of this folder in MB.', null=True),
        ),
        migrations.AlterField(
            model_name='dicomfolder',
            name='warn_size',
            field=models.PositiveIntegerField(blank=True, help_text='When to warn the admins by Email (used space in MB).', null=True),
        ),
    ]
