# Generated by Django 3.1.2 on 2020-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201004_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertask',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
