# Generated by Django 3.1.2 on 2020-10-08 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201007_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfertask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transfertask',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
