# Generated by Django 3.1.2 on 2020-10-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_auto_20201008_0432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferjob',
            name='job_type',
        ),
        migrations.AddField(
            model_name='transferjob',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.transferjob_set+', to='contenttypes.contenttype'),
        ),
    ]
