# Generated by Django 3.1.2 on 2020-10-11 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201011_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomnode',
            old_name='node_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='dicomnode',
            name='node_type',
        ),
    ]
