# Generated by Django 3.1.2 on 2020-10-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0007_auto_20201011_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomfolder',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='dicomnode',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='dicomserver',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='dicomnode',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_main.dicomnode_set+', to='contenttypes.contenttype'),
        ),
    ]
