# Generated by Django 3.1.2 on 2020-10-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201011_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dicomfolder',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dicomnode',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dicomserver',
            options={},
        ),
        migrations.RemoveField(
            model_name='dicomnode',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='transferjob',
            name='polymorphic_ctype',
        ),
    ]
