# Generated by Django 3.1.2 on 2020-10-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201012_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferjob',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='transfertask',
            old_name='created_at',
            new_name='created',
        ),
    ]
