# Generated by Django 3.1.2 on 2020-10-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201012_1119'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transferjob',
            name='main_transf_created_623d0e_idx',
        ),
        migrations.RenameField(
            model_name='transferjob',
            old_name='stopped_at',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='transferjob',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='transferjob',
            old_name='started_at',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='transfertask',
            old_name='stopped_at',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='transfertask',
            old_name='started_at',
            new_name='start',
        ),
        migrations.AddIndex(
            model_name='transferjob',
            index=models.Index(fields=['owner', 'status'], name='main_transf_owner_i_da6c9d_idx'),
        ),
    ]
