# Generated by Django 3.1.2 on 2020-10-12 16:02

import adit.main.fields
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201012_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='destination',
            field=adit.main.fields.InheritanceForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.dicomnode'),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='source',
            field=adit.main.fields.InheritanceForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.dicomnode'),
        ),
    ]
