# Generated by Django 3.1.3 on 2020-11-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomnode',
            name='active',
        ),
        migrations.AddField(
            model_name='dicomnode',
            name='destination_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomnode',
            name='source_active',
            field=models.BooleanField(default=True),
        ),
    ]
