# Generated by Django 3.1.3 on 2020-11-13 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertask',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid characters.', regex='[\\f\\n\\r\\\\]')]),
        ),
    ]
