# Generated by Django 3.1.3 on 2020-11-13 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201113_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='trial_protocol_id',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\')]),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='trial_protocol_name',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\')]),
        ),
        migrations.AlterField(
            model_name='transfertask',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]')]),
        ),
    ]
