# Generated by Django 3.1.3 on 2020-12-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201212_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferjob',
            options={'permissions': [('can_transfer_urgently', 'Can transfer urgently (prioritized and without scheduling).')]},
        ),
        migrations.RenameField(
            model_name='transferjob',
            old_name='transfer_directly',
            new_name='transfer_urgently',
        ),
    ]
