# Generated by Django 4.2.4 on 2023-08-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_institute"),
        ("core", "0006_dicomweb_config"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dicomnode",
            name="destination_active",
        ),
        migrations.RemoveField(
            model_name="dicomnode",
            name="source_active",
        ),
        migrations.CreateModel(
            name="DicomNodeInstituteAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source", models.BooleanField(default=False)),
                ("destination", models.BooleanField(default=False)),
                (
                    "dicom_node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="core.dicomnode",
                    ),
                ),
                (
                    "institute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.institute"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DICOM node institute accesses",
            },
        ),
        migrations.AddField(
            model_name="dicomnode",
            name="institutes",
            field=models.ManyToManyField(
                blank=True,
                related_name="dicom_nodes",
                through="core.DicomNodeInstituteAccess",
                to="accounts.institute",
            ),
        ),
        migrations.AddConstraint(
            model_name="dicomnodeinstituteaccess",
            constraint=models.UniqueConstraint(
                fields=("dicom_node", "institute"), name="unique_dicom_node_per_institute"
            ),
        ),
    ]
