# Generated by Django 4.2.7 on 2023-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0011_convert_dicom_node_accesses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dicomnode",
            name="institutes",
        ),
        migrations.AddField(
            model_name="dicomnode",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="dicom_nodes",
                through="core.DicomNodeGroupAccess",
                to="auth.group",
            ),
        ),
        migrations.DeleteModel(
            name="DicomNodeInstituteAccess",
        ),
    ]
