# Generated by Django 6.0.3 on 2026-03-29 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_add_max_search_results_to_dicomserver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dicomserver",
            name="max_search_results",
            field=models.PositiveIntegerField(
                default=200, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
