# Generated by Django 6.0.3 on 2026-04-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_review_fixes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomfolder',
            name='suspended',
            field=models.BooleanField(default=False, help_text='Suspended destinations skip processing (e.g. disk full).'),
        ),
    ]
