# Generated by Django 3.1.2 on 2020-10-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selective_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selectivetransferjob',
            options={'base_manager_name': 'objects'},
        ),
    ]
