# Generated by Django 3.1.3 on 2021-01-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selective_transfer", "0002_selectivetransfertask_retries"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selectivetransfertask",
            options={"ordering": ("task_id",)},
        ),
        migrations.AddField(
            model_name="selectivetransfertask",
            name="task_id",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
