# Generated by Django 3.1.3 on 2021-01-28 16:17

from django.db import migrations


def init_task_id(apps, _):
    SelectiveTransferJob = apps.get_model(
        "selective_transfer",
        "SelectiveTransferJob",
    )
    SelectiveTransferTask = apps.get_model(
        "selective_transfer",
        "SelectiveTransferTask",
    )

    for job in SelectiveTransferJob.objects.all():
        tasks = SelectiveTransferTask.objects.filter(job_id=job.id).order_by("id")
        for idx, task in enumerate(tasks):
            task.task_id = idx + 1
            task.save(update_fields=["task_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("selective_transfer", "0003_auto_20210128_1605"),
    ]

    operations = [
        migrations.RunPython(init_task_id, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="selectivetransfertask",
            unique_together={("job", "task_id")},
        ),
    ]
