# Generated by Django 4.2.5 on 2023-10-05 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0014_selectivetransferjob_send_finished_mail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selectivetransfertask",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveConstraint(
            model_name="selectivetransfertask",
            name="selectivetransfertask_unique_task_id_per_job",
        ),
        migrations.RemoveField(
            model_name="selectivetransfertask",
            name="task_id",
        ),
    ]
