# Generated by Django 4.2.5 on 2023-10-19 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0015_alter_selectivetransfertask_options_and_more"),
        ("selective_transfer", "0018_remove_selectivetransferjob_source_and_destination"),
    ]

    operations = []
