# Generated by Django 5.2 on 2025-06-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selective_transfer', '0027_switch_to_procrastinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectivetransferjob',
            name='convert_to_nifti',
            field=models.BooleanField(default=False),
        ),
    ]
