# Generated by Django 5.2.7 on 2025-10-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selective_transfer", "0028_selectivetransferjob_convert_to_nifti"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selectivetransfersettings",
            options={
                "permissions": (("download_study", "Download study"),),
                "verbose_name_plural": "Selective transfer settings",
            },
        ),
    ]
