# Generated by Django 5.2.7 on 2025-10-16 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("selective_transfer", "0029_alter_selectivetransfersettings_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="selectivetransfersettings",
            options={
                "permissions": (("can_download_study", "Can download study"),),
                "verbose_name_plural": "Selective transfer settings",
            },
        ),
    ]
