# Generated by Django 4.1.3 on 2022-12-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0005_auto_20210510_1645"),
    ]

    operations = [
        migrations.CreateModel(
            name="Access",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[("src", "Source"), ("dst", "Destination")],
                        editable=False,
                        max_length=3,
                    ),
                ),
                ("name", models.CharField(blank=True, editable=False, max_length=128, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="GroupAccess",
                        to="auth.group",
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.dicomnode",
                    ),
                ),
            ],
        ),
    ]
