# Generated by Django 4.0.6 on 2022-08-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qido_rs', '0002_remove_dicomqidojob_format_dicomqidojob_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='accession_number',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='modalities',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='patient_birth_date',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='series_count',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='series_description',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='series_uid',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='sop_uid',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='study_count',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='study_date',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='study_description',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='study_time',
        ),
        migrations.RemoveField(
            model_name='dicomqidoresult',
            name='study_uid',
        ),
        migrations.AddField(
            model_name='dicomqidoresult',
            name='query_results',
            field=models.JSONField(default=dict),
        ),
    ]
