# Generated by Django 3.0.7 on 2020-07-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selective_transfer_locked', models.BooleanField(default=False)),
                ('selective_transfer_suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='SelectiveTransferJob',
            fields=[
                ('dicomjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.DicomJob')),
            ],
            bases=('main.dicomjob',),
        ),
        migrations.CreateModel(
            name='SelectvieTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveIntegerField()),
                ('patient_id', models.CharField(max_length=64)),
                ('study_uid', models.CharField(max_length=64, null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='selective_transfer.SelectiveTransferJob')),
            ],
        ),
    ]
