# Generated by Django 3.0.7 on 2020-08-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selective_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectvieTransferRequest',
            new_name='SelectiveTransferRequest',
        ),
    ]
