# Generated by Django 3.0.7 on 2020-08-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selective_transfer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectiveTransferRequest',
        ),
    ]
