# Generated by Django 4.2.3 on 2023-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="fraction",
            field=models.TextField(default="toke", max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="token",
            name="token_string",
            field=models.TextField(max_length=128),
        ),
    ]
