# Generated by Django 4.2.3 on 2023-07-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0002_token_fraction_alter_token_token_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="client",
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
