# Generated by Django 3.0.7 on 2020-08-15 10:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_transfer_locked', models.BooleanField(default=False)),
                ('batch_transfer_suspended', models.BooleanField(default=False)),
                ('batch_slot_begin_time', models.TimeField(default=datetime.time(22, 0))),
                ('batch_slot_end_time', models.TimeField(default=datetime.time(8, 0))),
                ('batch_timeout', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name_plural': 'App settings',
            },
        ),
        migrations.CreateModel(
            name='BatchTransferJob',
            fields=[
                ('transferjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TransferJob')),
                ('project_name', models.CharField(max_length=150)),
                ('project_description', models.TextField(max_length=2000)),
                ('trial_protocol_id', models.CharField(blank=True, max_length=64)),
                ('trial_protocol_name', models.CharField(blank=True, max_length=64)),
                ('archive_password', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'permissions': (('can_cancel_batchtransferjob', 'Can cancel batch transfer job'),),
            },
            bases=('main.transferjob',),
        ),
        migrations.CreateModel(
            name='BatchTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.PositiveIntegerField()),
                ('patient_id', models.CharField(blank=True, max_length=64, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=324, null=True)),
                ('patient_birth_date', models.DateField()),
                ('accession_number', models.CharField(blank=True, max_length=16, null=True)),
                ('study_date', models.DateField()),
                ('modality', models.CharField(max_length=16)),
                ('pseudonym', models.CharField(blank=True, max_length=324, null=True)),
                ('status', models.CharField(choices=[('UN', 'Unprocessed'), ('SU', 'Success'), ('FA', 'Failure')], default='UN', max_length=2)),
                ('message', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='batch_transfer.BatchTransferJob')),
            ],
            options={
                'unique_together': {('request_id', 'job')},
            },
        ),
    ]
