# Generated by Django 3.0.7 on 2020-06-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransferJob',
            fields=[
                ('dicomjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.DicomJob')),
                ('project_name', models.CharField(max_length=150)),
                ('project_description', models.TextField(max_length=2000)),
                ('pseudonymize', models.BooleanField(default=True)),
                ('trial_protocol_id', models.CharField(blank=True, max_length=64)),
                ('trial_protocol_name', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'permissions': [('cancel_batchtransferjob', 'Can cancel batch transfer job')],
            },
            bases=('main.dicomjob',),
        ),
        migrations.CreateModel(
            name='BatchTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=16)),
                ('patient_id', models.CharField(max_length=64, null=True)),
                ('patient_name', models.CharField(max_length=256, null=True)),
                ('patient_birth_date', models.DateField()),
                ('study_date', models.DateField()),
                ('modality', models.CharField(max_length=16)),
                ('pseudonym', models.CharField(max_length=256, null=True)),
                ('status_code', models.CharField(choices=[('SU', 'Success'), ('WA', 'Warning'), ('ER', 'Error')], max_length=2, null=True)),
                ('status_message', models.CharField(max_length=256, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch_transfer.BatchTransferJob')),
            ],
            options={
                'unique_together': {('request_id', 'job')},
            },
        ),
    ]
