# Generated by Django 3.0.7 on 2020-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferrequest',
            name='processed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
