# Generated by Django 3.0.7 on 2020-08-17 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtransferjob',
            name='archive_password',
        ),
        migrations.RemoveField(
            model_name='batchtransferjob',
            name='trial_protocol_id',
        ),
        migrations.RemoveField(
            model_name='batchtransferjob',
            name='trial_protocol_name',
        ),
    ]
