# Generated by Django 3.0.7 on 2020-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferrequest',
            name='accession_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
