# Generated by Django 3.0.7 on 2020-06-13 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_batchtransferrequest_study_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_birth_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
