# Generated by Django 3.0.7 on 2020-08-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_batchtransferjob_batchtransferrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtransferjob',
            options={'permissions': (('cancel_batchtransferjob', 'Can cancel batch transfer job'),)},
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CA', 'Canceled'), ('SU', 'Success'), ('FA', 'Failure')], default='PE', max_length=2),
        ),
    ]
