# Generated by Django 3.0.7 on 2020-07-02 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_siteconfig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='lock_transfers',
            new_name='batch_transfer_locked',
        ),
    ]
