# Generated by Django 3.0.7 on 2020-08-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_auto_20200817_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('SU', 'Success'), ('FA', 'Failure')], default='PE', max_length=2),
        ),
    ]
