# Generated by Django 3.0.7 on 2020-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_batchtransferrequest_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='status',
            field=models.CharField(choices=[('UN', 'Unprocessed'), ('SU', 'Success'), ('WA', 'Warning'), ('ER', 'Error')], default='UN', max_length=2),
        ),
    ]
