# Generated by Django 3.0.7 on 2020-06-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200614_1829'),
        ('batch_transfer', '0003_auto_20200613_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTransferJob',
            fields=[
                ('transferjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TransferJob')),
                ('project_name', models.CharField(max_length=256)),
                ('project_description', models.TextField()),
            ],
            bases=('main.transferjob',),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch_transfer.BatchTransferJob'),
        ),
    ]
