# Generated by Django 3.0.7 on 2020-07-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20200715_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='status',
            field=models.CharField(choices=[('UN', 'Unprocessed'), ('SU', 'Success'), ('ER', 'Error')], default='UN', max_length=2),
        ),
    ]
