# Generated by Django 3.0.7 on 2020-06-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20200619_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferjob',
            name='pseudonymize',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='batchtransferjob',
            name='trial_protocol_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='batchtransferjob',
            name='trial_protocol_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
