# Generated by Django 3.0.7 on 2020-07-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20200725_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=324, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=324, null=True),
        ),
    ]
