# Generated by Django 3.0.7 on 2020-07-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20200702_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchtransferitem',
            old_name='row_id',
            new_name='request_id',
        ),
        migrations.AlterUniqueTogether(
            name='batchtransferitem',
            unique_together={('request_id', 'job')},
        ),
    ]
