# Generated by Django 3.0.7 on 2020-08-14 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0004_auto_20200726_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtransferjob',
            options={'permissions': (('can_cancel_batchtransferjob', 'Can cancel batch transfer job'),)},
        ),
        migrations.RemoveField(
            model_name='batchtransferjob',
            name='pseudonymize',
        ),
    ]
