# Generated by Django 3.0.7 on 2020-06-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0004_auto_20200614_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferjob',
            name='project_description',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='batchtransferjob',
            name='project_name',
            field=models.CharField(max_length=150),
        ),
    ]
