# Generated by Django 3.0.7 on 2020-07-16 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0005_auto_20200716_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='batch_slot_begin_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='batch_slot_end_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='batch_transfer_paused',
            field=models.BooleanField(default=False),
        ),
    ]
