# Generated by Django 3.0.7 on 2020-07-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0006_auto_20200716_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name_plural': 'App settings'},
        ),
        migrations.AddField(
            model_name='batchtransferjob',
            name='archive_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
