# Generated by Django 3.0.7 on 2020-07-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0008_appsettings_batch_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='batch_timeout',
            field=models.IntegerField(default=3),
        ),
    ]
