# Generated by Django 3.0.7 on 2020-07-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0009_auto_20200717_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='batch_transfer_paused',
            new_name='batch_transfer_suspended',
        ),
    ]
