# Generated by Django 4.2.4 on 2023-08-20 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_user_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("description", models.TextField(blank=True, max_length=1024)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="institutes", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
