# Generated by Django 4.2.7 on 2023-12-11 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_remove_institute_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Institute",
        ),
    ]
