# Generated by Django 5.1 on 2024-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Upload settings',
                'permissions': [('can_upload_data', 'Can upload data')],
                'default_permissions': (),
            },
        ),
    ]
