# Generated by Django 5.0.4 on 2024-07-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadtask',
            name='job',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='uploadtask',
            name='source',
        ),
        migrations.DeleteModel(
            name='UploadJob',
        ),
        migrations.DeleteModel(
            name='UploadTask',
        ),
    ]
