# Generated by Django 4.1.5 on 2023-04-26 13:58

import adit.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20210510_1645"),
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadjob",
            options={
                "permissions": [
                    ("can_process_urgently", "Can process urgently"),
                    ("can_transfer_unpseudonymized", "Can transfer unpseudonymized"),
                ]
            },
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="archive_password",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="destination",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.dicomnode",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="trial_protocol_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid backslash character",
                        regex="\\\\",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="uploadjob",
            name="trial_protocol_name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid backslash character",
                        regex="\\\\",
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="UploadTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task_id", models.PositiveIntegerField()),
                ("celery_task_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PE", "Pending"),
                            ("IP", "In Progress"),
                            ("CA", "Canceled"),
                            ("SU", "Success"),
                            ("WA", "Warning"),
                            ("FA", "Failure"),
                        ],
                        default="PE",
                        max_length=2,
                    ),
                ),
                ("retries", models.PositiveSmallIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                ("log", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                (
                    "patient_id",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Contains invalid backslash character",
                                regex="\\\\",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Contains invalid control characters.",
                                regex="[\\f\\n\\r]",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Contains invalid wildcard characters.",
                                regex="[\\*\\?]",
                            ),
                        ],
                    ),
                ),
                (
                    "study_uid",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid character in UID.", regex="^[\\d\\.]+$"
                            )
                        ],
                    ),
                ),
                (
                    "series_uids",
                    models.JSONField(
                        blank=True, null=True, validators=[adit.core.validators.validate_uids]
                    ),
                ),
                (
                    "pseudonym",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Contains invalid backslash character",
                                regex="\\\\",
                            ),
                            django.core.validators.RegexValidator(
                                inverse_match=True,
                                message="Contains invalid control characters.",
                                regex="[\\f\\n\\r]",
                            ),
                        ],
                    ),
                ),
                ("lines", models.JSONField(default=list)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="upload.uploadjob",
                    ),
                ),
            ],
            options={
                "ordering": ("task_id",),
                "abstract": False,
                "unique_together": {("job", "task_id")},
            },
        ),
    ]
