# Generated by Django 4.2.7 on 2023-11-13 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UploadSettings",
        ),
    ]
