# Generated by Django 5.0.4 on 2024-07-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_uploadjob'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadJob',
        ),
    ]
