# Generated by Django 5.0.4 on 2024-07-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_delete_uploadjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('upload_data_rights', 'Can upload data'), ('upload_data_view', 'Can view upload part')),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
