# Generated by Django 4.2.8 on 2024-01-02 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("upload", "0005_uploadjob_uploadtask_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadsettings",
            name="slot_begin_time",
        ),
        migrations.RemoveField(
            model_name="uploadsettings",
            name="slot_end_time",
        ),
        migrations.RemoveField(
            model_name="uploadsettings",
            name="transfer_timeout",
        ),
        migrations.RemoveField(
            model_name="uploadtask",
            name="celery_task_id",
        ),
    ]
