# Generated by Django 5.0.4 on 2024-07-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_alter_uploadpermission_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPermissionSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('upload_data_rights', 'Can upload data'), ('upload_data_view', 'Can view upload site')],
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.DeleteModel(
            name='UploadPermission',
        ),
    ]
