# Generated by Django 5.0.4 on 2024-07-09 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_alter_uploadpermissionsupport_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadpermissionsupport',
            options={'default_permissions': (), 'managed': False, 'permissions': [('can_upload_data', 'Can upload data')]},
        ),
    ]
