# Generated by Django 3.1.3 on 2021-11-23 11:48

import adit_server.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0006_auto_20211111_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtransfertask',
            name='series_uid',
        ),
        migrations.AddField(
            model_name='batchtransfertask',
            name='series_uids',
            field=models.JSONField(blank=True, null=True, validators=[adit_server.core.validators.validate_uids]),
        ),
    ]
