# Generated by Django 4.0.6 on 2022-07-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0010_alter_batchtransferjob_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferjob',
            name='ethics_application_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
