# Generated by Django 4.2.5 on 2023-10-23 11:10

from django.db import migrations
from django.apps import AppConfig


def move_text_to_array_fields(apps: AppConfig, schema_editor):
    BatchTransferTask = apps.get_model("batch_transfer.BatchTransferTask")
    for task in BatchTransferTask.objects.all():
        task.lines_new = [int(x.strip()) for x in task.lines.split(",") if x.strip()]
        task.series_uids_new = [x.strip() for x in task.series_uids.split(",") if x.strip()]
        task.save()


def move_array_to_text_fields(apps: AppConfig, schema_editor):
    BatchTransferTask = apps.get_model("batch_transfer.BatchTransferTask")
    for task in BatchTransferTask.objects.all():
        task.lines = ", ".join([str(x) for x in task.lines_new])
        task.series_uids = ", ".join(task.series_uids_new)
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0022_batchtransfertask_lines_new_and_more"),
    ]

    operations = [migrations.RunPython(move_text_to_array_fields, move_array_to_text_fields)]
