# Generated by Django 3.1.2 on 2020-10-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='misc_settings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
