# Generated by Django 4.1.3 on 2022-12-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="RelatedGroup",
            field=models.ManyToManyField(related_name="GroupMember", to="auth.group"),
        ),
    ]
