# Generated by Django 4.2.7 on 2023-12-10 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0005_institute"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_users",
                to="auth.group",
            ),
        ),
    ]
