# Generated by Django 4.2.7 on 2023-12-10 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_copy_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="user",
            name="preferences",
        ),
    ]
