# Generated by Django 4.2.3 on 2023-07-23 23:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0005_alter_token_options_remove_token_expires_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="expiry_time",
            new_name="expires",
        ),
    ]
