# Generated by Django 3.1.3 on 2020-12-21 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyfinderquery',
            name='study_description',
        ),
    ]
