# Generated by Django 4.2.3 on 2023-08-06 08:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="misc_settings",
            new_name="preferences",
        ),
    ]
