# Generated by Django 3.2.2 on 2021-05-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selective_transfer', '0005_selectivetransfertask_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectivetransferjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='selectivetransfersettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='selectivetransfertask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
