# Generated by Django 4.2.2 on 2023-06-23 08:25

import adit_server.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0010_alter_selectivetransferjob_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selectivetransfertask",
            name="series_uids",
            field=models.TextField(
                blank=True, default="", validators=[adit_server.core.validators.validate_uids]
            ),
            preserve_default=False,
        ),
    ]
