# Generated by Django 4.2.4 on 2023-09-03 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_dicom_node_institute_access"),
        ("selective_transfer", "0014_selectivetransferjob_send_finished_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectivetransfertask",
            name="destination",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.dicomnode",
            ),
        ),
        migrations.AddField(
            model_name="selectivetransfertask",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.dicomnode",
            ),
        ),
    ]
