# Generated by Django 4.2.4 on 2023-09-03 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0017_alter_selectivetransfertask_source_destination_not_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectivetransferjob",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="selectivetransferjob",
            name="source",
        ),
    ]
