# Generated by Django 4.2.5 on 2023-10-23 11:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0019_merge_20231019_0724"),
    ]

    operations = [
        migrations.AddField(
            model_name="selectivetransfertask",
            name="series_uids_new",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
