# Generated by Django 4.2.5 on 2023-10-23 11:09

from django.db import migrations
from django.apps import AppConfig


def move_text_to_array_fields(apps: AppConfig, schema_editor):
    SelectiveTransferTask = apps.get_model("selective_transfer.SelectiveTransferTask")
    for task in SelectiveTransferTask.objects.all():
        task.series_uids_new = [x.strip() for x in task.series_uids.split(",") if x.strip()]
        task.save()


def move_array_to_text_fields(apps: AppConfig, schema_editor):
    SelectiveTransferTask = apps.get_model("selective_transfer.SelectiveTransferTask")
    for task in SelectiveTransferTask.objects.all():
        task.series_uids = ", ".join(task.series_uids_new)
        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0020_selectivetransfertask_series_uids_new"),
    ]

    operations = [migrations.RunPython(move_text_to_array_fields, move_array_to_text_fields)]
