# Generated by Django 4.2.5 on 2023-10-23 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0022_remove_selectivetransfertask_series_uids"),
    ]

    operations = [
        migrations.RenameField(
            model_name="selectivetransfertask",
            old_name="series_uids_new",
            new_name="series_uids",
        ),
    ]
