# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("selective_transfer", "0025_alter_selectivetransfertask_series_uids"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="selectivetransfersettings",
            name="slot_begin_time",
        ),
        migrations.RemoveField(
            model_name="selectivetransfersettings",
            name="slot_end_time",
        ),
        migrations.RemoveField(
            model_name="selectivetransfersettings",
            name="transfer_timeout",
        ),
        migrations.RemoveField(
            model_name="selectivetransfertask",
            name="celery_task_id",
        ),
    ]
