# Generated by Django 3.0.7 on 2020-06-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200616_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomserver',
            name='find_query_model',
            field=models.CharField(choices=[('PR', 'Patient Root'), ('SR', 'Study Root')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='get_query_model',
            field=models.CharField(choices=[('PR', 'Patient Root'), ('SR', 'Study Root')], default='PR', max_length=2),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='move_query_model',
            field=models.CharField(choices=[('PR', 'Patient Root'), ('SR', 'Study Root')], default='PR', max_length=2),
        ),
    ]
