# Generated by Django 6.0.3 on 2026-03-22 20:48

import django.core.validators
import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0016_add_max_search_results_to_dicomserver'),
        ('procrastinate', '0041_post_retry_failed_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MassTransferSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mass transfer settings',
            },
        ),
        migrations.CreateModel(
            name='MassTransferJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('IP', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='UV', max_length=2)),
                ('urgent', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, default='')),
                ('send_finished_mail', models.BooleanField(default=False)),
                ('convert_to_nifti', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('trial_protocol_id', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\')])),
                ('trial_protocol_name', models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\')])),
                ('archive_password', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('partition_granularity', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=16)),
                ('pseudonymize', models.BooleanField(default=True)),
                ('pseudonym_salt', models.CharField(blank=True, default=secrets.token_hex, max_length=64)),
                ('filters_json', models.JSONField(blank=True, help_text='Inline filter configuration as a JSON list of filter objects.', null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.dicomnode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_jobs', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.dicomnode')),
            ],
            options={
                'permissions': [('can_process_urgently', 'Can process urgently'), ('can_transfer_unpseudonymized', 'Can transfer unpseudonymized')],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassTransferTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='PE', max_length=2)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('partition_start', models.DateTimeField()),
                ('partition_end', models.DateTimeField()),
                ('partition_key', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='mass_transfer.masstransferjob')),
                ('queued_job', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='procrastinate.procrastinatejob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.dicomnode')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MassTransferVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition_key', models.CharField(max_length=64)),
                ('pseudonym', models.CharField(blank=True, default='', max_length=64)),
                ('patient_id', models.CharField(blank=True, default='', max_length=64)),
                ('accession_number', models.CharField(blank=True, default='', max_length=64)),
                ('study_instance_uid', models.CharField(max_length=64)),
                ('study_instance_uid_pseudonymized', models.CharField(blank=True, default='', max_length=128)),
                ('series_instance_uid', models.CharField(max_length=64)),
                ('series_instance_uid_pseudonymized', models.CharField(blank=True, default='', max_length=128)),
                ('modality', models.CharField(blank=True, default='', max_length=16)),
                ('study_description', models.CharField(blank=True, default='', max_length=256)),
                ('series_description', models.CharField(blank=True, default='', max_length=256)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('study_datetime', models.DateTimeField()),
                ('institution_name', models.CharField(blank=True, default='', max_length=128)),
                ('number_of_images', models.PositiveIntegerField(default=0)),
                ('converted_file', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('exported', 'Exported'), ('converted', 'Converted'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=16)),
                ('log', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='mass_transfer.masstransferjob')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='volumes', to='mass_transfer.masstransfertask')),
            ],
            options={
                'ordering': ('study_datetime', 'series_instance_uid'),
            },
        ),
        migrations.AddIndex(
            model_name='masstransferjob',
            index=models.Index(fields=['owner', 'status'], name='mass_transf_owner_i_c363b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='masstransfervolume',
            constraint=models.UniqueConstraint(fields=('job', 'series_instance_uid'), name='mass_transfer_unique_series_per_job'),
        ),
    ]
