# Generated by Django 5.2.8 on 2026-02-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0002_two_phase_task_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masstransfertask',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='masstransfertask',
            name='study_instance_uid',
        ),
        migrations.RemoveField(
            model_name='masstransfertask',
            name='task_type',
        ),
    ]
