# Generated by Django 6.0.3 on 2026-03-29 15:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mass_transfer", "0003_fix_queued_job_on_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masstransferjob",
            name="filters_json",
            field=models.JSONField(
                blank=True,
                help_text="JSON list of filter objects. Valid keys: modality, institution_name, apply_institution_on_study, study_description, series_description, series_number, min_age, max_age.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="masstransfertask",
            name="patient_id",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid backslash character",
                        regex="\\\\",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid control characters.",
                        regex="[\\f\\n\\r]",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid wildcard characters.",
                        regex="[\\*\\?]",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="masstransfertask",
            name="pseudonym",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid backslash character",
                        regex="\\\\",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid control characters.",
                        regex="[\\f\\n\\r]",
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="masstransfertask",
            name="series_uids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=64,
                    validators=[
                        django.core.validators.RegexValidator(
                            message="Invalid character in UID.", regex="^[\\d\\.]+$"
                        )
                    ],
                ),
                blank=True,
                default=list,
            ),
        ),
        migrations.AlterField(
            model_name="masstransfertask",
            name="study_uid",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Invalid character in UID.", regex="^[\\d\\.]+$"
                    )
                ],
            ),
        ),
    ]
