# Generated by Django 6.0.3 on 2026-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_review_fixes"),
        ("mass_transfer", "0004_sync_transfertask_fields"),
        ("procrastinate", "0041_post_retry_failed_job"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masstransfertask",
            options={},
        ),
        migrations.AddConstraint(
            model_name="masstransfertask",
            constraint=models.CheckConstraint(
                condition=models.Q(("partition_start__lt", models.F("partition_end"))),
                name="mass_transfer_partition_start_before_end",
            ),
        ),
    ]
