# Generated by Django 5.2.8 on 2026-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0004_anonymization_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masstransfervolume',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('exported', 'Exported'), ('converted', 'Converted'), ('skipped', 'Skipped'), ('error', 'Error')], default='pending', max_length=16),
        ),
    ]
