# Generated by Django 5.2.8 on 2026-03-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0005_skipped_volume_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='masstransfervolume',
            name='series_instance_uid_pseudonymized',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='masstransfervolume',
            name='study_instance_uid_pseudonymized',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='MassTransferAssociation',
        ),
    ]
