# Generated by Django 6.0.7 on 2026-07-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mass_transfer", "0005_add_partition_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="masstransfervolume",
            name="retriable",
            field=models.BooleanField(default=False),
        ),
    ]
