# Generated by Django 6.0.7 on 2026-07-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mass_transfer", "0006_masstransfervolume_retriable"),
    ]

    operations = [
        migrations.AddField(
            model_name="masstransfertask",
            name="anonymizer_seed",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
