# Generated by Django 5.2.8 on 2026-03-05 11:19

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0006_replace_association_with_volume_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='masstransferjob',
            name='pseudonym_salt',
            field=models.CharField(default=secrets.token_hex, max_length=64),
        ),
    ]
