# Generated by Django 5.2.8 on 2026-03-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0007_add_pseudonym_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masstransfervolume',
            name='export_cleaned',
        ),
        migrations.RemoveField(
            model_name='masstransfervolume',
            name='exported_folder',
        ),
    ]
