# Generated by Django 5.2.8 on 2026-03-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0008_remove_exported_folder_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masstransfervolume',
            name='series_instance_uid_pseudonymized',
        ),
        migrations.RemoveField(
            model_name='masstransfervolume',
            name='study_instance_uid_pseudonymized',
        ),
    ]
