# Generated by Django 5.2.8 on 2026-03-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0010_re_add_pseudonymized_uid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='masstransferjob',
            name='filters_json',
            field=models.JSONField(blank=True, help_text='Inline filter configuration as a JSON list of filter objects.', null=True),
        ),
    ]
