# Generated by Django 6.0.3 on 2026-03-19 15:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mass_transfer', '0011_add_filters_json'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masstransferjob',
            options={'permissions': [('can_process_urgently', 'Can process urgently'), ('can_transfer_unpseudonymized', 'Can transfer unpseudonymized')]},
        ),
        migrations.AddField(
            model_name='masstransferjob',
            name='archive_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='masstransferjob',
            name='trial_protocol_id',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\')]),
        ),
        migrations.AddField(
            model_name='masstransferjob',
            name='trial_protocol_name',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\')]),
        ),
        migrations.AlterField(
            model_name='masstransferjob',
            name='anonymization_mode',
            field=models.CharField(choices=[('none', 'None'), ('pseudonymize', 'Pseudonymize'), ('pseudonymize_with_linking', 'Pseudonymize with linking')], default='none', max_length=32),
        ),
    ]
