# Generated by Django 4.2.11 on 2024-03-26 17:32

from django.db import migrations
from django.conf import settings

def update_or_create_site_profile(apps, _):
    SiteProfileModel = apps.get_model("common", "SiteProfile")

    SiteProfileModel.objects.update_or_create(
        site_id=settings.SITE_ID,
        defaults={
            "meta_keywords": settings.SITE_META_KEYWORDS,
            "meta_description": settings.SITE_META_DESCRIPTION,
            "project_url": settings.SITE_PROJECT_URL,
        },
    )

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_update_or_create_site'),
        ("sites", "0002_alter_domain_unique"),
    ]

    operations = [
        migrations.RunPython(update_or_create_site_profile),
    ]
