# Generated by Django 4.2.4 on 2023-08-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0010_alter_token_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TokenSettings",
        ),
        migrations.AlterField(
            model_name="token",
            name="client",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="token",
            name="fraction",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="token",
            name="token_hashed",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
