# Generated by Django 3.0.7 on 2020-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
