# Generated by Django 4.2.3 on 2023-08-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_rename_misc_settings_user_preferences"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferences",
            field=models.JSONField(default=dict),
        ),
    ]
