from django.urls import path
from .views import (
    SelectiveTransferJobListView,
    SelectiveTransferJobCreateView,
    SelectiveTransferJobDetailView,
    SelectiveTransferJobDeleteView,
    SelectiveTransferJobVerifyView,
    SelectiveTransferJobCancelView,
    SelectiveTransferJobResumeView,
    SelectiveTransferJobRetryView,
    SelectiveTransferJobRestartView,
    SelectiveTransferTaskDetailView,
)

urlpatterns = [
    path(
        "jobs/",
        SelectiveTransferJobListView.as_view(),
        name="selective_transfer_job_list",
    ),
    path(
        "jobs/new/",
        SelectiveTransferJobCreateView.as_view(),
        name="selective_transfer_job_create",
    ),
    path(
        "jobs/<int:pk>/",
        SelectiveTransferJobDetailView.as_view(),
        name="selective_transfer_job_detail",
    ),
    path(
        "jobs/<int:pk>/delete/",
        SelectiveTransferJobDeleteView.as_view(),
        name="selective_transfer_job_delete",
    ),
    path(
        "jobs/<int:pk>/verify/",
        SelectiveTransferJobVerifyView.as_view(),
        name="selective_transfer_job_verify",
    ),
    path(
        "jobs/<int:pk>/cancel/",
        SelectiveTransferJobCancelView.as_view(),
        name="selective_transfer_job_cancel",
    ),
    path(
        "jobs/<int:pk>/resume/",
        SelectiveTransferJobResumeView.as_view(),
        name="selective_transfer_job_resume",
    ),
    path(
        "jobs/<int:pk>/retry/",
        SelectiveTransferJobRetryView.as_view(),
        name="selective_transfer_job_retry",
    ),
    path(
        "jobs/<int:pk>/restart/",
        SelectiveTransferJobRestartView.as_view(),
        name="selective_transfer_job_restart",
    ),
    path(
        "jobs/<int:job_id>/tasks/<int:task_id>/",
        SelectiveTransferTaskDetailView.as_view(),
        name="selective_transfer_task_detail",
    ),
]
