# Generated by Django 4.0.3 on 2022-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauthtoken',
            name='expires',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='restauthtoken',
            name='client',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restauthtoken',
            name='expiry_time',
            field=models.DateTimeField(),
        ),
    ]
