# Generated by Django 4.0.3 on 2022-05-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0002_restauthtoken_expires_alter_restauthtoken_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restauthtoken',
            name='expires',
        ),
    ]
