# Generated by Django 4.0.3 on 2022-05-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0003_remove_restauthtoken_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauthtoken',
            name='expires',
            field=models.BooleanField(default=True),
        ),
    ]
