# Generated by Django 4.0.3 on 2022-05-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0004_restauthtoken_expires'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauthtoken',
            options={'permissions': [('can_manage_rest_auth_tokens', 'Can manage REST authentication tokens')]},
        ),
        migrations.RemoveField(
            model_name='restauthtoken',
            name='expires',
        ),
    ]
