# Generated by Django 4.0.3 on 2022-05-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0005_alter_restauthtoken_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restauthtoken',
            options={'permissions': [('manage_auth_tokens', 'Can manage REST authentication tokens')]},
        ),
    ]
