# Generated by Django 4.0.3 on 2022-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('token_authentication', '0006_alter_restauthtoken_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauthtoken',
            name='expires',
            field=models.BooleanField(default=True),
        ),
    ]
