# Generated by Django 4.2.3 on 2023-07-27 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("token_authentication", "0008_alter_token_token_hashed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="author",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="token",
            name="client",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="token",
            unique_together={("owner", "client")},
        ),
    ]
