# Generated by Django 4.2.4 on 2023-08-28 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0011_delete_tokensettings_alter_token_client_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="token",
            name="unique_client_per_user",
        ),
        migrations.RenameField(
            model_name="token",
            old_name="client",
            new_name="description",
        ),
    ]
