# Generated by Django 4.2.4 on 2023-08-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("token_authentication", "0012_remove_token_unique_client_per_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="description",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
