# Generated by Django 5.0.6 on 2024-07-07 20:31

import django.db.models.deletion
from django.apps import AppConfig
from django.db import migrations, models

from adit_radis_shared.common.utils.migration_utils import procrastinate_on_delete_sql


def increase_attempt(apps: AppConfig, schema_editor):
    ExampleTransferTask = apps.get_model("example_app.ExampleTransferTask")
    ExampleTransferTask.objects.update(attempts=models.F("attempts") + 1)

def decrease_attempt(apps: AppConfig, schema_editor):
    ExampleTransferTask = apps.get_model("example_app.ExampleTransferTask")
    ExampleTransferTask.objects.update(attempts=models.F("attempts") - 1)


class Migration(migrations.Migration):

    dependencies = [
        ("example_app", "0001_initial"),
        ("procrastinate", "0028_add_cancel_states"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exampletransfertask",
            old_name="retries",
            new_name="attempts",
        ),
        migrations.AddField(
            model_name="exampletransfertask",
            name="queued_job",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="procrastinate.procrastinatejob",
            ),
        ),
        migrations.RunSQL(
            sql=procrastinate_on_delete_sql("example_app", "exampletransfertask"),
            reverse_sql=procrastinate_on_delete_sql("example_app", "exampletransfertask", reverse=True),
        ),
        migrations.RunPython(increase_attempt, decrease_attempt),
    ]
