from django.urls import path
from .views import (
    SelectiveTransferJobListAPIView, 
    SelectiveTransferJobDetailAPIView,
    QueryStudyAPIView, 
    QuerySeriesAPIView,
    RetrieveStudyAPIView,
    RetrieveSeriesAPIView,
)

urlpatterns = [
    path(
        "selective-transfer-jobs/",
        SelectiveTransferJobListAPIView.as_view(),
    ),
    path(
        "selective-transfer-jobs/<int:id>/",
        SelectiveTransferJobDetailAPIView.as_view(),
    ),
    path(
        "query/<str:pacs>/studies/",
        QueryStudyAPIView.as_view(),
    ),
    path(
        "query/<str:pacs>/studies/<str:StudyInstanceUID>/",
        QueryStudyAPIView.as_view(),
    ),
    path(
        "query/<str:pacs>/studies/<str:StudyInstanceUID>/series/",
        QuerySeriesAPIView.as_view(),
    ),
    path(
        "query/<str:pacs>/studies/<str:StudyInstanceUID>/series/<str:SeriesInstanceUID>/",
        QuerySeriesAPIView.as_view(),
    ),
    path(
        "retrieve/<str:pacs>/studies/",
        RetrieveStudyAPIView.as_view(),
    ),
    path(
        "retrieve/<str:pacs>/studies/<str:StudyInstanceUID>/",
        RetrieveStudyAPIView.as_view(),
    ),
    path(
        "retrieve/<str:pacs>/studies/<str:StudyInstanceUID>/<str:mode>/",
        RetrieveStudyAPIView.as_view(),
    ),
    path(
        "retrieve/<str:pacs>/series/",
        RetrieveSeriesAPIView.as_view(),
    ),
    path(
        "retrieve/<str:pacs>/studies/<str:StudyInstanceUID>/series/<str:SeriesInstanceUID>/",
        RetrieveSeriesAPIView.as_view(),
    ),
]
