# Generated by Django 3.0.7 on 2020-06-24 19:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(max_length=64, unique=True)),
                ('node_type', models.CharField(choices=[('SV', 'Server'), ('PA', 'Path')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DicomPath',
            fields=[
                ('dicomnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.DicomNode')),
                ('path', models.CharField(max_length=256)),
            ],
            bases=('main.dicomnode',),
        ),
        migrations.CreateModel(
            name='DicomServer',
            fields=[
                ('dicomnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.DicomNode')),
                ('ae_title', models.CharField(max_length=16, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('find_query_model', models.CharField(choices=[('PR', 'Patient Root'), ('SR', 'Study Root')], default='PR', max_length=2)),
                ('move_query_model', models.CharField(choices=[('PR', 'Patient Root'), ('SR', 'Study Root')], default='PR', max_length=2)),
                ('get_query_model', models.CharField(choices=[('PR', 'Patient Root'), ('SR', 'Study Root')], default='PR', max_length=2)),
            ],
            bases=('main.dicomnode',),
        ),
        migrations.CreateModel(
            name='DicomJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('BA', 'Batch transfer job')], max_length=2)),
                ('status', models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('PR', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('CP', 'Completed'), ('DE', 'Deleted')], default='UV', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('stopped_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.DicomNode')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.DicomNode')),
            ],
        ),
    ]
