# Generated by Django 3.0.7 on 2020-06-13 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DicomNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeId', models.CharField(max_length=64)),
                ('nodeName', models.CharField(max_length=128)),
                ('nodeType', models.CharField(choices=[('SV', 'Server'), ('PA', 'Path')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DicomPath',
            fields=[
                ('dicomnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.DicomNode')),
                ('path', models.CharField(max_length=256)),
            ],
            bases=('main.dicomnode',),
        ),
        migrations.CreateModel(
            name='DicomServer',
            fields=[
                ('dicomnode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.DicomNode')),
                ('ae_title', models.CharField(max_length=16, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
            ],
            bases=('main.dicomnode',),
        ),
        migrations.CreateModel(
            name='TransferJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobType', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('PR', 'In Progress'), ('CA', 'Canceled'), ('CP', 'Completed')], max_length=2)),
                ('created_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(null=True)),
                ('stopped_at', models.DateTimeField(null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.DicomNode')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.DicomNode')),
            ],
        ),
    ]
