# Generated by Django 3.0.7 on 2020-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomnode',
            name='nodeId',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
