# Generated by Django 3.0.7 on 2020-06-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomjob',
            name='status',
            field=models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('PR', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('CP', 'Completed'), ('DE', 'Deleted')], default='UV', max_length=2),
        ),
    ]
