# Generated by Django 3.0.7 on 2020-08-17 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferjob',
            name='paused_at',
        ),
        migrations.AddField(
            model_name='transferjob',
            name='archive_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transferjob',
            name='trial_protocol_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transferjob',
            name='trial_protocol_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='status',
            field=models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('IP', 'In Progress'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='UV', max_length=2),
        ),
        migrations.CreateModel(
            name='TransferTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('SU', 'Success'), ('FA', 'Failure')], default='PE', max_length=2)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('stopped_at', models.DateTimeField(null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='main.TransferJob')),
            ],
        ),
        migrations.CreateModel(
            name='DicomStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=64)),
                ('pseudonym', models.CharField(blank=True, max_length=324, null=True)),
                ('study_uid', models.CharField(blank=True, max_length=64, null=True)),
                ('modalities', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_list', to='main.TransferTask')),
            ],
        ),
        migrations.CreateModel(
            name='DicomSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=64)),
                ('pseudonym', models.CharField(blank=True, max_length=324, null=True)),
                ('study_uid', models.CharField(blank=True, max_length=64, null=True)),
                ('series_uid', models.CharField(blank=True, max_length=64, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_list', to='main.TransferTask')),
            ],
        ),
    ]
