# Generated by Django 3.0.7 on 2020-07-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomjob',
            name='paused_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dicomjob',
            name='status',
            field=models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('IP', 'In Progress'), ('PA', 'Paused'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='UV', max_length=2),
        ),
    ]
