# Generated by Django 3.0.7 on 2020-06-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transferjob_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='status',
            field=models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('PR', 'In Progress'), ('CA', 'Canceled'), ('CP', 'Completed')], default='UV', max_length=2),
        ),
    ]
