# Generated by Django 3.0.7 on 2020-07-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200716_0712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name_plural': 'App settings'},
        ),
    ]
