# Generated by Django 3.0.7 on 2020-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200613_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transferjob',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('PR', 'In Progress'), ('CA', 'Canceled'), ('CP', 'Completed')], default='PE', max_length=2),
        ),
    ]
