# Generated by Django 3.0.7 on 2020-07-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200716_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomserver',
            name='find_query_model',
        ),
        migrations.RemoveField(
            model_name='dicomserver',
            name='get_query_model',
        ),
        migrations.RemoveField(
            model_name='dicomserver',
            name='move_query_model',
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='patient_root_query_model_find',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='patient_root_query_model_get',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dicomserver',
            name='patient_root_query_model_move',
            field=models.BooleanField(default=True),
        ),
    ]
