# Generated by Django 3.0.7 on 2020-06-16 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200616_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferjob',
            old_name='target',
            new_name='destination',
        ),
    ]
