# Generated by Django 3.0.7 on 2020-06-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200613_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dicomnode',
            old_name='nodeId',
            new_name='node_id',
        ),
        migrations.RenameField(
            model_name='dicomnode',
            old_name='nodeType',
            new_name='node_type',
        ),
        migrations.RenameField(
            model_name='transferjob',
            old_name='jobType',
            new_name='job_type',
        ),
        migrations.RemoveField(
            model_name='dicomnode',
            name='nodeName',
        ),
        migrations.AddField(
            model_name='dicomnode',
            name='node_name',
            field=models.CharField(default='kjk', max_length=128, verbose_name='Node Name'),
            preserve_default=False,
        ),
    ]
