# Generated by Django 3.0.7 on 2020-06-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200614_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomnode',
            name='node_name',
            field=models.CharField(max_length=128),
        ),
    ]
