# Generated by Django 3.0.7 on 2020-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200717_1245'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dicomjob',
            index=models.Index(fields=['created_by', 'status'], name='main_dicomj_created_4cea60_idx'),
        ),
    ]
