# Generated by Django 3.0.7 on 2020-07-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200718_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicomjob',
            name='status',
            field=models.CharField(choices=[('UV', 'Unverified'), ('PE', 'Pending'), ('IP', 'In Progress'), ('PA', 'Paused'), ('CI', 'Canceling'), ('CA', 'Canceled'), ('CP', 'Completed')], default='UV', max_length=2),
        ),
    ]
