# Generated by Django 3.0.7 on 2020-06-14 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200614_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferjob',
            name='job_type',
            field=models.CharField(choices=[('BA', 'Batch transfer job')], max_length=2),
        ),
    ]
