# Generated by Django 3.0.7 on 2020-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200619_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dicomnode',
            name='node_id',
        ),
        migrations.AlterField(
            model_name='dicomnode',
            name='node_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
