# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dicom_explorer", "0002_dicomexplorersettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dicomexplorersettings",
            name="slot_begin_time",
        ),
        migrations.RemoveField(
            model_name="dicomexplorersettings",
            name="slot_end_time",
        ),
        migrations.RemoveField(
            model_name="dicomexplorersettings",
            name="transfer_timeout",
        ),
    ]
