# Generated by Django 3.0.7 on 2020-06-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_auto_20200619_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferjob',
            name='trial_protocol_id',
            field=models.TextField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='batchtransferjob',
            name='trial_protocol_name',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
