version: "3.8"

x-app:
  &default-app
  image: radis_dev:latest
  volumes:
    - ..:/app
  env_file:
    - ../.env.dev
  environment:
    ENABLE_REMOTE_DEBUGGING: 0
    DJANGO_SETTINGS_MODULE: "radis.settings.development"

services:
  web:
    <<: *default-app
    build:
      target: development
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      # Cave, overwrites the above anchor
      - ..:/app
      - vscode-server:/root/.vscode-server/extensions
      - vscode-server-insiders:/root/.vscode-server-insiders/extensions
    command: >
      bash -c "
        wait-for-it -s postgres:5432 -t 60 && 
        ./manage.py migrate &&
        ./manage.py collectstatic --no-input &&
        ./manage.py populate_dev_db &&
        wait-for-it -s vespa:19071 -t 60 &&
        ./manage.py setup_vespa --generate --deploy &&
        ./manage.py populate_dev_vespa &&
        ./manage.py runserver 0.0.0.0:8000
      "

  worker_default:
    <<: *default-app
    command: |
      ./manage.py celery_worker -Q default_queue --autoreload

  worker_report:
    <<: *default-app
    command: |
      ./manage.py celery_worker -Q report_queue --autoreload

  celery_beat:
    <<: *default-app
    command: |
      ./manage.py celery_beat --autoreload

  flower:
    <<: *default-app

  postgres:
    environment:
      POSTGRES_PASSWORD: "postgres"

  vespa:
    environment:
      # Reduce memory usage of Vespa during development (espcially on Cloud IDEs), see
      # https://docs.vespa.ai/en/operations/node-setup.html#memory-settings
      VESPA_CONFIGSERVER_JVMARGS: "-Xms32M -Xmx128M"
      VESPA_CONFIGPROXY_JVMARGS: "-Xms32M -Xmx32M"

volumes:
  vscode-server:
  vscode-server-insiders:
