# Generated by Django 3.1.2 on 2020-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continuous_transfer_locked', models.BooleanField(default=False)),
                ('continuous_transfer_suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
