# Generated by Django 3.1.3 on 2020-11-16 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuousTransferJob',
            fields=[
                ('transferjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.transferjob')),
                ('project_name', models.CharField(max_length=150)),
                ('project_description', models.TextField(max_length=2000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            bases=('core.transferjob',),
        ),
        migrations.CreateModel(
            name='ContinuousTransferSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Continuous transfer settings',
            },
        ),
        migrations.CreateModel(
            name='DataElementFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_tag', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('EQ', 'equals'), ('EN', 'equals not'), ('CO', 'contains'), ('CN', 'contains not'), ('RE', 'regex'), ('RN', 'regex not')], default='EQ', max_length=2)),
                ('filter_value', models.CharField(max_length=200)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('order', models.SmallIntegerField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='continuous_transfer.continuoustransferjob')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
