# Generated by Django 3.1.2 on 2020-10-07 10:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuoustransferjob',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continuoustransferjob',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DataElementFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dicom_tag', models.CharField(max_length=100)),
                ('filter_type', models.CharField(choices=[('EQ', 'equals'), ('CO', 'contains'), ('CN', 'contains not'), ('RE', 'regexp')], default='CO', max_length=2)),
                ('filter_value', models.CharField(max_length=200)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='continuous_transfer.continuoustransferjob')),
            ],
        ),
    ]
