# Generated by Django 3.1.2 on 2020-10-18 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelementfilter',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
