# Generated by Django 3.1.3 on 2020-12-13 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuoustransfersettings',
            name='slot_begin_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Must be set in UTC time zone.'),
        ),
        migrations.AddField(
            model_name='continuoustransfersettings',
            name='slot_end_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Must be set in UTC time zone.'),
        ),
        migrations.AddField(
            model_name='continuoustransfersettings',
            name='transfer_timeout',
            field=models.IntegerField(default=3),
        ),
    ]
