# Generated by Django 3.1.2 on 2020-10-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0002_auto_20201007_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuoustransferjob',
            options={'base_manager_name': 'objects'},
        ),
    ]
