# Generated by Django 3.1.2 on 2020-10-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0002_dataelementfilter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelementfilter',
            name='filter_type',
            field=models.CharField(choices=[('EQ', 'equals'), ('EN', 'equals not'), ('CO', 'contains'), ('CN', 'contains not'), ('RE', 'regex'), ('RN', 'regex not')], default='EQ', max_length=2),
        ),
    ]
