# Generated by Django 3.1.2 on 2020-10-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0003_auto_20201011_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continuoustransferjob',
            options={},
        ),
    ]
