# Generated by Django 3.1.2 on 2020-10-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0003_auto_20201019_0854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataelementfilter',
            options={'ordering': ('order',)},
        ),
    ]
