# Generated by Django 3.1.3 on 2021-11-23 12:31

import adit.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0007_auto_20211112_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continuoustransfertask',
            name='series_uid',
        ),
        migrations.AddField(
            model_name='continuoustransfertask',
            name='series_uids',
            field=models.JSONField(blank=True, null=True, validators=[adit.core.validators.validate_uid_list]),
        ),
    ]
