# Generated by Django 3.2.8 on 2022-02-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_transfer', '0008_auto_20211123_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continuoustransferjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='continuoustransfersettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='continuoustransfertask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dataelementfilter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
