# Generated by Django 4.2.5 on 2023-09-12 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("announcement", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Core settings",
            },
        ),
    ]
