# Generated by Django 3.1.3 on 2021-01-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_query', '0002_auto_20210120_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchquerytask',
            name='retries',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
