# Generated by Django 3.1.3 on 2021-01-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_query', '0004_auto_20210127_1721'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchquerytask',
            options={'ordering': ('task_id',)},
        ),
        migrations.RenameField(
            model_name='batchquerytask',
            old_name='batch_id',
            new_name='task_id',
        ),
        migrations.AlterUniqueTogether(
            name='batchquerytask',
            unique_together={('job', 'task_id')},
        ),
    ]
