# Generated by Django 3.2.8 on 2022-02-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_query', '0009_auto_20220222_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchquerytask',
            old_name='batch_ids',
            new_name='lines',
        ),
    ]
