# Generated by Django 4.0.3 on 2022-05-01 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_query', '0011_alter_batchqueryjob_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchqueryresult',
            name='series_number',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid wildcard characters.', regex='[\\*\\?]')]),
        ),
        migrations.AddField(
            model_name='batchquerytask',
            name='series_number',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid wildcard characters.', regex='[\\*\\?]')]),
        ),
    ]
