# Generated by Django 4.1.7 on 2023-03-21 12:43

import adit.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0012_batchqueryresult_series_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchquerytask",
            name="series_number",
        ),
        migrations.AddField(
            model_name="batchquerytask",
            name="series_numbers",
            field=models.JSONField(
                blank=True, null=True, validators=[adit.core.validators.validate_series_numbers]
            ),
        ),
        migrations.AddField(
            model_name="batchquerytask",
            name="study_description",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="batchqueryresult",
            name="study_description",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid backslash character",
                        regex="\\\\",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid control characters.",
                        regex="[\\f\\n\\r]",
                    ),
                    django.core.validators.RegexValidator(
                        inverse_match=True,
                        message="Contains invalid wildcard characters.",
                        regex="[\\*\\?]",
                    ),
                ],
            ),
        ),
    ]
