# Generated by Django 4.2.2 on 2023-06-23 08:25

import adit.core.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0014_alter_batchqueryresult_series_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchqueryresult",
            name="modalities",
            field=models.TextField(
                blank=True, default="", validators=[adit.core.validators.validate_modalities]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batchquerytask",
            name="lines",
            field=models.TextField(
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="batchquerytask",
            name="modalities",
            field=models.TextField(
                blank=True, default="", validators=[adit.core.validators.validate_modalities]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batchquerytask",
            name="series_numbers",
            field=models.TextField(
                blank=True, default="", validators=[adit.core.validators.validate_series_numbers]
            ),
            preserve_default=False,
        ),
    ]
