# Generated by Django 4.1.7 on 2023-03-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0014_alter_batchqueryresult_series_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchqueryresult",
            name="series_number",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
