# Generated by Django 4.2.2 on 2023-06-23 09:46

import json
from django.apps import AppConfig
from django.db import migrations


def convert_json_to_text(apps: AppConfig, schema_editor):
    BatchQueryTask = apps.get_model("batch_query.BatchQueryTask")
    for query in BatchQueryTask.objects.all():
        if not query.lines:
            query.lines = ""
        else:
            query.lines = ", ".join(json.loads(query.lines))

        if not query.modalities:
            query.modalities = ""
        else:
            query.modalities = ", ".join(json.loads(query.modalities))

        if not query.series_numbers:
            query.series_number = ""
        else:
            query.series_numbers = ", ".join(json.loads(query.series_numbers))

        query.save()

    BatchQueryResult = apps.get_model("batch_query.BatchQueryResult")
    for result in BatchQueryResult.objects.all():
        if not result.modalities:
            result.modalities = ""
        else:
            result.modalities = ", ".join(json.loads(result.modalities))

        result.save()


def convert_text_to_json(apps: AppConfig, schema_editor):
    BatchQueryTask = apps.get_model("batch_query.BatchQueryTask")
    for query in BatchQueryTask.objects.all():
        if not query.lines:
            query.lines = "[]"
        else:
            query.lines = json.dumps(list(map(str.strip, query.lines.split(","))))

        if not query.modalities:
            query.modalities = "null"
        else:
            query.modalities = json.dumps(list(map(str.strip, query.modalities.split(","))))

        if not query.series_numbers:
            query.series_number = "null"
        else:
            query.series_numbers = json.dumps(list(map(str.strip, query.series_numbers.split(","))))

        query.save()

    BatchQueryResult = apps.get_model("batch_query.BatchQueryResult")
    for result in BatchQueryResult.objects.all():
        if not result.modalities:
            result.modalities = None
        else:
            result.modalities = json.dumps(list(map(str.strip, result.modalities.split(","))))

        result.save()


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0015_alter_batchqueryresult_modalities_and_more"),
    ]

    operations = [migrations.RunPython(convert_json_to_text, convert_text_to_json)]
