# Generated by Django 4.2.2 on 2023-06-23 09:46

import json
from django.apps import AppConfig
from django.db import migrations


def convert_json_to_text(apps: AppConfig, schema_editor):
    BatchQueryResult = apps.get_model("batch_query.BatchQueryResult")
    for result in BatchQueryResult.objects.all():
        if not result.modalities:
            result.modalities = ""
        else:
            result.modalities = ", ".join(json.loads(result.modalities))

        result.save()

    BatchQueryTask = apps.get_model("batch_query.BatchQueryTask")
    for task in BatchQueryTask.objects.all():
        if not task.lines:
            task.lines = ""
        else:
            task.lines = ", ".join(json.loads(task.lines))

        if not task.modalities:
            task.modalities = ""
        else:
            task.modalities = ", ".join(json.loads(task.modalities))

        if not task.series_numbers:
            task.series_number = ""
        else:
            task.series_numbers = ", ".join(json.loads(task.series_numbers))

        task.save()


def convert_text_to_json(apps: AppConfig, schema_editor):
    BatchQueryResult = apps.get_model("batch_query.BatchQueryResult")
    for result in BatchQueryResult.objects.all():
        if not result.modalities:
            result.modalities = None
        else:
            result.modalities = json.dumps(list(map(str.strip, result.modalities.split(","))))

        result.save()

    BatchQueryTask = apps.get_model("batch_query.BatchQueryTask")
    for task in BatchQueryTask.objects.all():
        if not task.lines:
            task.lines = "[]"
        else:
            task.lines = json.dumps(list(map(str.strip, task.lines.split(","))))

        if not task.modalities:
            task.modalities = "null"
        else:
            task.modalities = json.dumps(list(map(str.strip, task.modalities.split(","))))

        if not task.series_numbers:
            task.series_number = "null"
        else:
            task.series_numbers = json.dumps(list(map(str.strip, task.series_numbers.split(","))))

        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0015_alter_batchqueryresult_modalities_and_more"),
    ]

    operations = [migrations.RunPython(convert_json_to_text, convert_text_to_json)]
