# Generated by Django 4.2.4 on 2023-09-03 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0022_alter_batchquerytask_source_not_null"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchqueryjob",
            name="source",
        ),
    ]
