# Generated by Django 4.2.5 on 2023-10-19 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0020_alter_batchquerytask_options_and_more"),
        ("batch_query", "0023_remove_batchqueryjob_source"),
    ]

    operations = []
