# Generated by Django 4.2.5 on 2023-10-23 11:10

from django.db import migrations
from django.apps import AppConfig


def move_text_to_array_fields(apps: AppConfig, schema_editor):
    BatchQueryTask = apps.get_model("batch_query.BatchQueryTask")
    for query in BatchQueryTask.objects.all():
        query.lines_new = [int(x.strip()) for x in query.lines.split(",") if x.strip()]
        query.modalities_new = [x.strip() for x in query.modalities.split(",") if x.strip()]
        query.series_numbers_new = [x.strip() for x in query.series_numbers.split(",") if x.strip()]
        query.save()

    BatchQueryResult = apps.get_model("batch_query.BatchQueryResult")
    for result in BatchQueryResult.objects.all():
        result.modalities_new = [x.strip() for x in result.modalities.split(",") if x.strip()]
        result.save()


def move_array_to_text_fields(apps: AppConfig, schema_editor):
    BatchQueryTask = apps.get_model("batch_query.BatchQueryTask")
    for query in BatchQueryTask.objects.all():
        query.lines = ", ".join([str(x) for x in query.lines_new])
        query.modalities = ", ".join(query.modalities_new)
        query.series_numbers = ", ".join(query.series_numbers_new)
        query.save()

    BatchQueryResult = apps.get_model("batch_query.BatchQueryResult")
    for result in BatchQueryResult.objects.all():
        result.modalities = ", ".join(query.modalities_new)
        result.save()


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0025_batchqueryresult_modalities_new_and_more"),
    ]

    operations = [migrations.RunPython(move_text_to_array_fields, move_array_to_text_fields)]
