# Generated by Django 4.2.5 on 2023-10-23 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0026_text_to_array_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchqueryresult",
            name="modalities",
        ),
        migrations.RemoveField(
            model_name="batchquerytask",
            name="lines",
        ),
        migrations.RemoveField(
            model_name="batchquerytask",
            name="modalities",
        ),
        migrations.RemoveField(
            model_name="batchquerytask",
            name="series_numbers",
        ),
    ]
