# Generated by Django 4.2.5 on 2023-10-23 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0027_remove_batchqueryresult_modalities_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batchqueryresult",
            old_name="modalities_new",
            new_name="modalities",
        ),
        migrations.RenameField(
            model_name="batchquerytask",
            old_name="lines_new",
            new_name="lines",
        ),
        migrations.RenameField(
            model_name="batchquerytask",
            old_name="modalities_new",
            new_name="modalities",
        ),
        migrations.RenameField(
            model_name="batchquerytask",
            old_name="series_numbers_new",
            new_name="series_numbers",
        ),
    ]
