# Generated by Django 4.2.5 on 2023-10-25 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0029_alter_batchquerytask_modalities_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchqueryresult",
            name="series_number",
            field=models.CharField(
                blank=True,
                max_length=12,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\s*[-+]?[0-9]+\\s*$", "Invalid string representation of a number."
                    )
                ],
            ),
        ),
    ]
