# Generated by Django 3.1.3 on 2021-01-20 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchqueryresult',
            name='accession_number',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid wildcard characters.', regex='[\\*\\?]')]),
        ),
        migrations.AlterField(
            model_name='batchquerytask',
            name='accession_number',
            field=models.CharField(blank=True, max_length=32, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid wildcard characters.', regex='[\\*\\?]')]),
        ),
    ]
