# Generated by Django 3.1.3 on 2021-01-27 17:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_query', '0003_batchquerytask_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchqueryresult',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]')]),
        ),
        migrations.AddField(
            model_name='batchquerytask',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]')]),
        ),
    ]
