# Generated by Django 4.1.7 on 2023-03-29 14:13

import adit_server.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0013_revise_batchquerytask_series_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchqueryresult",
            name="series_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=12,
                validators=[adit_server.core.validators.validate_series_number],
            ),
            preserve_default=False,
        ),
    ]
