# Generated by Django 4.2.5 on 2023-10-05 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0019_batchqueryjob_send_finished_mail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchquerytask",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveConstraint(
            model_name="batchquerytask",
            name="batchquerytask_unique_task_id_per_job",
        ),
        migrations.RemoveField(
            model_name="batchquerytask",
            name="task_id",
        ),
    ]
