# Generated by Django 4.2.4 on 2023-09-03 20:53

from django.apps import AppConfig
from django.db import migrations


def set_source_in_tasks(apps: AppConfig, schema_editor):
    BatchQueryJob = apps.get_model("batch_query.BatchQueryJob")
    for job in BatchQueryJob.objects.all():
        for task in job.tasks.all():
            task.source_id = job.source_id
            task.save()


def set_source_in_jobs(apps: AppConfig, schema_editor):
    BatchQueryJob = apps.get_model("batch_query.BatchQueryJob")
    for job in BatchQueryJob.objects.all():
        task = job.tasks.first()
        job.source_id = task.source_id
        job.save()


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0020_batchquerytask_source"),
    ]

    operations = [migrations.RunPython(set_source_in_tasks, set_source_in_jobs)]
