# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_query", "0030_alter_batchqueryresult_series_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchquerysettings",
            name="slot_begin_time",
        ),
        migrations.RemoveField(
            model_name="batchquerysettings",
            name="slot_end_time",
        ),
        migrations.RemoveField(
            model_name="batchquerysettings",
            name="transfer_timeout",
        ),
        migrations.RemoveField(
            model_name="batchquerytask",
            name="celery_task_id",
        ),
    ]
