# Generated by Django 4.2.8 on 2023-12-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("reports", "0002_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="institutes",
        ),
        migrations.AddField(
            model_name="report",
            name="groups",
            field=models.ManyToManyField(related_name="reports", to="auth.group"),
        ),
    ]
