# Generated by Django 5.2.8 on 2025-12-08 20:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dicom_web", "0003_add_dicom_web_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_last_accessed",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("total_transfer_size", models.BigIntegerField(default=0)),
                ("total_number_requests", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-time_last_accessed"],
                        name="dicom_web_a_time_la_866621_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner",), name="unique_owner_api_usage"
                    )
                ],
            },
        ),
    ]
