# Generated by Django 3.1.3 on 2020-12-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferjob',
            name='archive_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
