# Generated by Django 3.1.3 on 2020-12-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchtransfersettings',
            old_name='batch_slot_begin_time',
            new_name='slot_begin_time',
        ),
        migrations.RenameField(
            model_name='batchtransfersettings',
            old_name='batch_slot_end_time',
            new_name='slot_end_time',
        ),
        migrations.RenameField(
            model_name='batchtransfersettings',
            old_name='batch_timeout',
            new_name='transfer_timeout',
        ),
    ]
