# Generated by Django 3.1.3 on 2020-11-13 16:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='accession_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid characters.', regex='[\\f\\n\\r\\\\]'), django.core.validators.RegexValidator(inverse_match=True, message='No wildcards allowed.', regex='[\\*\\?]')]),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='modality',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid characters.', regex='[\\f\\n\\r\\\\]'), django.core.validators.RegexValidator(inverse_match=True, message='No wildcards allowed.', regex='[\\*\\?]')]),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_birth_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='No date range allowed.', regex='-')]),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_id',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid characters.', regex='[\\f\\n\\r\\\\]'), django.core.validators.RegexValidator(inverse_match=True, message='No wildcards allowed.', regex='[\\*\\?]')]),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_name',
            field=models.CharField(blank=True, max_length=324, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid characters.', regex='[\\f\\n\\r\\\\]'), django.core.validators.RegexValidator(inverse_match=True, message='No wildcards allowed.', regex='[\\*\\?]')]),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid characters.', regex='[\\f\\n\\r\\\\]'), django.core.validators.RegexValidator(inverse_match=True, message='No wildcards allowed.', regex='[\\*\\?]')]),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='study_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='No date range allowed.', regex='-')]),
        ),
    ]
