# Generated by Django 3.1.2 on 2020-10-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='PE', max_length=2),
        ),
    ]
