# Generated by Django 3.1.3 on 2020-12-18 10:40

import adit.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_batchtransferjob_archive_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferrequest',
            name='log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='batchtransfertask',
            name='series_uids',
            field=models.JSONField(blank=True, null=True, validators=[adit.core.validators.validate_uids]),
        ),
        migrations.AlterField(
            model_name='batchtransfertask',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('IP', 'In Progress'), ('CA', 'Canceled'), ('SU', 'Success'), ('WA', 'Warning'), ('FA', 'Failure')], default='PE', max_length=2),
        ),
    ]
