# Generated by Django 3.1.2 on 2020-10-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_auto_20201022_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtransferrequest',
            options={'ordering': ('row_key',)},
        ),
    ]
