# Generated by Django 3.1.2 on 2020-10-01 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_batchtransferjob_batchtransferrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appsettings',
            name='batch_slot_begin_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Must be set in UTC time.'),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='batch_slot_end_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Must be set in UTC time.'),
        ),
    ]
