# Generated by Django 3.1.1 on 2020-09-07 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_batchtransferjob_batchtransferrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchtransferrequest',
            old_name='processed_at',
            new_name='started_at',
        ),
    ]
