# Generated by Django 3.1.3 on 2020-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0002_auto_20201113_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_birth_date',
            field=models.DateField(blank=True, error_messages={'invalid': 'Invalid date format.'}, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='study_date',
            field=models.DateField(blank=True, error_messages={'invalid': 'Invalid date format.'}, null=True),
        ),
    ]
