# Generated by Django 3.1.2 on 2020-10-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20201023_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtransferrequest',
            options={'ordering': ('row_number',)},
        ),
        migrations.RenameField(
            model_name='batchtransferrequest',
            old_name='row_key',
            new_name='row_number',
        ),
        migrations.AlterUniqueTogether(
            name='batchtransferrequest',
            unique_together={('row_number', 'job')},
        ),
    ]
