# Generated by Django 3.1.1 on 2020-09-07 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20200907_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtransferrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batchtransferrequest',
            name='stopped_at',
            field=models.DateTimeField(null=True),
        ),
    ]
