# Generated by Django 3.1.2 on 2020-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0003_auto_20201001_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
