# Generated by Django 3.1.2 on 2020-10-07 10:36

import adit.main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0004_auto_20201007_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='pseudonym',
            field=models.CharField(blank=True, max_length=64, null=True, validators=[adit.main.validators.validate_pseudonym]),
        ),
    ]
