# Generated by Django 3.1.2 on 2020-11-02 09:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0004_auto_20201026_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransfersettings',
            name='batch_slot_begin_time',
            field=models.TimeField(default=datetime.time(22, 0), help_text='Must be set in UTC time zone.'),
        ),
        migrations.AlterField(
            model_name='batchtransfersettings',
            name='batch_slot_end_time',
            field=models.TimeField(default=datetime.time(8, 0), help_text='Must be set in UTC time zone.'),
        ),
    ]
