# Generated by Django 3.1.2 on 2020-10-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0005_auto_20201007_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='modality',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='patient_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='study_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
