# Generated by Django 3.1.3 on 2021-11-11 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0005_auto_20210510_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtransfertask',
            name='series_uids',
        ),
        migrations.AddField(
            model_name='batchtransfertask',
            name='series_uid',
            field=models.CharField(blank=True, max_length=64, validators=[django.core.validators.RegexValidator(message='Invalid character in UID.', regex='^[\\d\\.]+$')]),
        ),
        migrations.AlterField(
            model_name='batchtransferjob',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batchtransfersettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='batchtransfertask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
