# Generated by Django 3.1.2 on 2020-10-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0006_auto_20201009_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='batchtransferrequest',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
