# Generated by Django 3.1.2 on 2020-10-09 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0006_auto_20201008_0432'),
        ('batch_transfer', '0007_auto_20201009_0949'),
    ]

    operations = [
    ]
