# Generated by Django 3.1.2 on 2020-10-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0008_merge_20201009_0801'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchtransferjob',
            options={'base_manager_name': 'objects'},
        ),
    ]
