# Generated by Django 3.1.2 on 2020-10-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_transfer', '0011_auto_20201012_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchtransferrequest',
            old_name='stopped_at',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='batchtransferrequest',
            old_name='started_at',
            new_name='start',
        ),
    ]
