# Generated by Django 4.2.2 on 2023-06-23 08:25

import adit.core.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0011_batchtransferjob_ethics_application_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchtransfertask",
            name="lines",
            field=models.TextField(
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="batchtransfertask",
            name="series_uids",
            field=models.TextField(
                blank=True, default="", validators=[adit.core.validators.validate_uids]
            ),
            preserve_default=False,
        ),
    ]
