# Generated by Django 4.2.2 on 2023-06-23 10:04

import json
from django.apps import AppConfig
from django.db import migrations


def convert_json_to_text(apps: AppConfig, schema_editor):
    BatchTransferTask = apps.get_model("batch_transfer.BatchTransferTask")
    for task in BatchTransferTask.objects.all():
        if not task.lines:
            task.lines = ""
        else:
            task.lines = ", ".join(json.loads(task.lines))

        if not task.series_uids:
            task.series_uids = ""
        else:
            task.series_uids = ", ".join(json.loads(task.series_uids))

        task.save()


def convert_text_to_json(apps: AppConfig, schema_editor):
    BatchTransferTask = apps.get_model("batch_transfer.BatchTransferTask")
    for task in BatchTransferTask.objects.all():
        if not task.lines:
            task.lines = "[]"
        else:
            task.lines = json.dumps(list(map(str.strip, task.lines.split(","))))

        if not task.series_uids:
            task.series_uids = None
        else:
            task.series_uids = json.dumps(list(map(str.strip, task.series_uids.split(","))))

        task.save()


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0012_alter_batchtransfertask_lines_and_more"),
    ]

    operations = [migrations.RunPython(convert_json_to_text, convert_text_to_json)]
