# Generated by Django 4.2.3 on 2023-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0014_alter_batchtransfertask_lines"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="batchtransfertask",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="batchtransfertask",
            constraint=models.UniqueConstraint(
                fields=("job", "task_id"), name="batchtransfertask_unique_task_id_per_job"
            ),
        ),
    ]
