# Generated by Django 4.2.5 on 2023-10-05 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0016_batchtransferjob_send_finished_mail"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchtransfertask",
            options={"ordering": ("id",)},
        ),
        migrations.RemoveConstraint(
            model_name="batchtransfertask",
            name="batchtransfertask_unique_task_id_per_job",
        ),
        migrations.RemoveField(
            model_name="batchtransfertask",
            name="task_id",
        ),
    ]
