# Generated by Django 4.2.5 on 2023-10-19 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0017_alter_batchtransfertask_options_and_more"),
        ("batch_transfer", "0020_remove_batchtransferjob_source_and_destination"),
    ]

    operations = []
