# Generated by Django 4.2.5 on 2023-10-25 07:52

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("batch_transfer", "0026_alter_batchtransfertask_series_uids"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchtransfertask",
            name="series_uids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    max_length=64,
                    validators=[
                        django.core.validators.RegexValidator(
                            message="Invalid character in UID.", regex="^[\\d\\.]+$"
                        )
                    ],
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
