# Generated by Django 5.2 on 2025-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0002_switch_to_procrastinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampletransferjob',
            name='convert_to_nifti',
            field=models.BooleanField(default=False),
        ),
    ]
