# Generated by Django 4.1.7 on 2023-02-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PermissionSupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
            options={
                "permissions": (("query_dicom_server", "Query DICOM Server"),),
                "managed": False,
                "default_permissions": (),
            },
        ),
    ]
