# Generated by Django 3.1.3 on 2020-12-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('query_dicom_server', 'Query DICOM Server'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
