# Generated by Django 6.1.1 on 2026-10-01 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0017_review_fixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('suspended', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Router settings',
            },
        ),
        migrations.CreateModel(
            name='RouterSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calling_ae_title', models.CharField(blank=True, default='', help_text='The AE title the server sends from. Leave empty to use its AE title.', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid backslash character', regex='\\\\'), django.core.validators.RegexValidator(inverse_match=True, message='Contains invalid control characters.', regex='[\\f\\n\\r]')])),
                ('enabled', models.BooleanField(default=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='router_sender', to='core.dicomserver')),
            ],
            options={
                'ordering': ('calling_ae_title',),
            },
        ),
    ]
